#!/usr/bin/env sh

PRJ_ROOT=$(dirname $(dirname $(realpath $0)))

main() {
    ${PRJ_ROOT}/scripts/clean && \
    cmake -B build -DBUILD_TESTS=ON && \
    printf 'scripts:build %s\n' 'configuration done.' && \
    cmake --build build && \
    printf 'scripts:build %s\n' 'build done.'
}

main $@